import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Download, RefreshCw } from 'lucide-react';

interface ResultViewProps {
  content: string;
  onReset: () => void;
}

const ResultView: React.FC<ResultViewProps> = ({ content, onReset }) => {
  
  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ideation-lab-analysis.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-5xl mx-auto animate-fade-in">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <span className="w-2 h-8 bg-blue-500 rounded-full inline-block"></span>
          Strategic Analysis
        </h2>
        <div className="flex gap-3">
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors font-medium text-sm border border-slate-600"
          >
            <Download size={16} />
            Export Markdown
          </button>
          <button
            onClick={onReset}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors font-medium text-sm shadow-lg shadow-blue-900/20"
          >
            <RefreshCw size={16} />
            New Idea
          </button>
        </div>
      </div>

      <div className="bg-slate-800/80 rounded-2xl p-8 border border-slate-700 shadow-2xl backdrop-blur-sm">
        <div className="markdown-body">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {content}
            </ReactMarkdown>
        </div>
      </div>
      
      <div className="mt-8 text-center text-slate-500 text-sm pb-12">
        Generated by Gemini 3 Pro • Ideation Lab AI
      </div>
    </div>
  );
};

export default ResultView;
